name: 'Drupal Search'
description: 'Drupal recipe for setting up search using Solr.'
type: 'Site'

install:
  - config
  - search_api
  - search_api_solr

config:
  # Allow config import to continue if config already exists.
  strict: false
  import:
    search_api: '*'
    search_api_solr: '*'
